controllers:
    resource:
        path: ../src/Controller/Mvc/
        namespace: App\Controller\Mvc
    type: attribute
api-controllers:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    type: attribute
    prefix: /api
    name_prefix: api_
