version: "3.9"

networks:
    main:

services:
    php-fpm:
        build:
            context: "./php-fpm"
            dockerfile: "Dockerfile"
        container_name: "php-fpm"
        networks:
            - "main"
        ports:
            - "9000:9000"
            - "8000:8000"
        volumes:
            - "./php-fpm/conf/:/usr/local/etc/"
            - "./php-fpm/log/:/var/log/php-fpm/"
            - "./shared/:/shared/"
            - "../src/:/var/www/html/"
        depends_on:
            - "postgresql"
    postgresql:
        build:
            context: "./postgresql"
            dockerfile: "Dockerfile"
        container_name: "postgresql"
        networks:
            - "main"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "server"
        volumes:
            - "./postgresql/data/:/var/lib/postgresql/data/"
            - "./shared/:/shared/"
    nginx:
        build:
            context: "./nginx"
            dockerfile: "Dockerfile"
        container_name: nginx
        networks:
            - "main"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx/conf/:/etc/nginx/"
            - "./nginx/log/:/var/log/nginx/"
            - "./shared/:/shared/"
            - "../src/:/var/www/html/"
        depends_on:
            - "php-fpm"
